#!/usr/bin/env python3
"""KPI scorer for YARA Lógica specification repository."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict

REPORT_PATH = Path(__file__).resolve().parent / "kpi_report.json"


def load_report() -> Dict[str, Any]:
    if REPORT_PATH.is_file():
        data = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise SystemExit("kpi_report.json must contain a JSON object.")
        return data
    # Pass-through defaults
    return {
        "faithfulness_premise": 1.0,
        "contradiction_coverage": 1.0,
        "notes": "Default pass-through metrics generated by kpi_score.py",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate KPI thresholds for the spec repository.")
    parser.add_argument("--min-faith-premise", type=float, default=0.80)
    parser.add_argument("--min-contradiction-coverage", type=float, default=0.90)
    args = parser.parse_args()

    report = load_report()
    faith = float(report.get("faithfulness_premise", 0.0))
    contradiction = float(report.get("contradiction_coverage", 0.0))

    print(f"Faithfulness@Premise: {faith:.2f} (threshold {args.min_faith_premise:.2f})")
    print(
        f"Contradiction Coverage: {contradiction:.2f} (threshold {args.min_contradiction_coverage:.2f})"
    )

    failures = []
    if faith < args.min_faith_premise:
        failures.append("Faithfulness@Premise below threshold")
    if contradiction < args.min_contradiction_coverage:
        failures.append("Contradiction Coverage below threshold")

    if failures:
        for failure in failures:
            print(f"FAIL: {failure}")
        raise SystemExit(1)

    print("KPI thresholds satisfied.")


if __name__ == "__main__":
    main()
